// src/PlayersCommands.jsx
import React, { Component } from 'react'

export class PlayersCommands extends Component {
  render () {
    const hidedPipClasses = [
      'btn',
      'btn-sm',
      'btn-link',
      'hide-on-mobile',
      'mx-1',
      this.props.aboveChat ? 'd-none' : ''
    ]
    return (
      <div className='commands text-center'>
        <button onClick={this.props.handleFlipX} type='button' className={hidedPipClasses.join(' ')} data-bs-toggle='tooltip' data-bs-placement='bottom' title='Placer à gauche ou à droite'>
          <i className='bi bi-arrow-left-right' />
        </button>
        <button onClick={this.props.handleFlipY} type='button' className={hidedPipClasses.join(' ')} data-bs-toggle='tooltip' data-bs-placement='bottom' title='Placer en haut ou en bas'>
          <i className='bi bi-arrow-down-up' />
        </button>
        <button onClick={this.props.handlePipActive} type='button' className={hidedPipClasses.join(' ')} data-bs-toggle='tooltip' data-bs-placement='bottom' title='Activer/désactiver le lecteur'>
          <i className='bi bi-eye' />
        </button>
        <button onClick={this.props.handleSwitchPlayer} type='button' className='btn btn-sm btn-link hide-on-mobile mx-1' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Inverser les deux lecteurs'>
          <i className='bi bi-arrow-repeat' />
        </button>
        <div className='btn-group dropup mx-1' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Changer la langue du cast'>
          <button type='button' className='btn btn-sm btn-link dropdown-toggle' data-bs-toggle='dropdown' aria-expanded='false'>
            <i className='bi bi-chat-dots' />
          </button>
          <ul id='casts' className='dropdown-menu'>
            {
              this.props.casts.map((cast, index) => {
                const href = this.props.host ? `${cast.hash}&host=${this.props.host}` : `${cast.hash}`
                return cast.disabled || <li key={index}><a onClick={this.props.handleChangeCast} className='dropdown-item' href={href}>{cast.name}</a></li>
              })
            }
          </ul>
        </div>
        <div className='btn-group dropup mx-1' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Choix du thème'>
          <button type='button' className='btn btn-sm btn-link dropdown-toggle' data-bs-toggle='dropdown' aria-expanded='false'>
            <i className='bi bi-palette' />
          </button>
          <ul id='themes' className='dropdown-menu'>
            {this.props.themes.map((theme, index) => theme.disabled ? null : <li key={index}><a onClick={this.props.handleSwitchTheme} className='dropdown-item' href={theme.hash}>{theme.name}</a></li>)}
          </ul>
        </div>
      </div>
    )
  }
}

// src/app/components/players-commands/players-commands.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  input,
  model,
} from "@angular/core";
import { Cast, Pip, Position } from "../../app.model";
import { CASTS } from "../../cast";

@Component({
  selector: "app-players-commands",
  imports: [CommonModule],
  templateUrl: "players-commands.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlayersCommandsComponent {
  public selectedCast = input<Cast>();
  public host = input<string>();
  public pip = model<Pip>();
  public pipActive = model<boolean>();
  public pipAboveChat = model<boolean>();
  public position = model<Position>();

  protected casts = CASTS.filter(cast => !cast.disabled);

  onChangeSwap() {
    this.pip.update(pip => (pip === Pip.Cast ? Pip.Host : Pip.Cast));
  }
  onChangeActive() {
    this.pipActive.update(pipActive => !(pipActive ?? true));
  }
  onChangeX() {
    this.position.update(position => ({
      flipX: !(position?.flipX ?? true),
      flipY: position?.flipY ?? true,
    }));
  }
  onChangeY() {
    this.position.update(position => ({
      flipX: position?.flipX ?? true,
      flipY: !(position?.flipY ?? true),
    }));
  }
}

@if (!pipAboveChat()) {
  <button
    type="button"
    class="btn btn-sm hide-on-mobile mx-1"
    data-bs-toggle="tooltip"
    data-bs-placement="bottom"
    title="Placer à gauche ou à droite"
    (click)="onChangeX()">
    <i class="bi bi-arrow-left-right"></i>
  </button>
  <button
    type="button"
    class="btn btn-sm hide-on-mobile mx-1"
    data-bs-toggle="tooltip"
    data-bs-placement="bottom"
    title="Placer en haut ou en bas"
    (click)="onChangeY()">
    <i class="bi bi-arrow-down-up"></i>
  </button>
  <button
    type="button"
    class="btn btn-sm hide-on-mobile mx-1"
    data-bs-toggle="tooltip"
    data-bs-placement="bottom"
    [title]="(pipActive() ? 'Masquer' : 'Afficher') + ' le petit lecteur'"
    (click)="onChangeActive()">
    @if (!pipActive()) {
      <i class="bi bi-eye"></i>
    } @else {
      <i class="bi bi-eye-slash"></i>
    }
  </button>
}

<button
  type="button"
  class="btn btn-sm hide-on-mobile mx-1"
  data-bs-toggle="tooltip"
  data-bs-placement="bottom"
  title="Echanger les lecteurs"
  (click)="onChangeSwap()">
  @if (pip() === "host") {
    <i class="bi bi-pip"></i>
  } @else if (pip() === "cast") {
    <i class="bi bi-pip-fill"></i>
  }
</button>
<div
  class="btn-group dropup mx-1"
  data-bs-toggle="tooltip"
  data-bs-placement="bottom"
  title="Changer de cast">
  <button
    type="button"
    class="btn btn-sm dropdown-toggle"
    data-bs-toggle="dropdown"
    aria-expanded="false">
    <i class="bi bi-youtube"></i>
  </button>
  <ul id="casts" class="dropdown-menu">
    @for (cast of casts; track cast.hash) {
      <li>
        <a
          class="dropdown-item"
          [href]="host() ? cast.hash + '&host=' + host : cast.hash"
          [class.active]="selectedCast() === cast">
          {{ cast.name }}
        </a>
      </li>
    }
  </ul>
</div>
