// src/ChatCommands.jsx
import React, { Component } from 'react'

export class ChatCommands extends Component {
  render () {
    const hidePipClasses = [
      'btn',
      'btn-sm',
      'btn-link',
      'hide-on-mobile',
      'mx-1',
      this.props.pipActive && this.props.aboveChat && this.props.showChat ? '' : 'd-none'
    ]
    const abovePipClasses = [
      'btn',
      'btn-sm',
      'btn-link',
      'hide-on-mobile',
      'mx-1',
      this.props.showChat ? '' : 'd-none'
    ]
    return (
      <div className='commands text-center hide-on-mobile'>
        <button onClick={this.props.handlePipActive} type='button' className={hidePipClasses.join(' ')} data-bs-toggle='tooltip' data-bs-placement='bottom' title='Masquer le lecteur'>
          <i className='bi bi-eye-slash' />
        </button>
        <button onClick={this.props.handleAboveChat} type='button' className={abovePipClasses.join(' ')} data-bs-toggle='tooltip' data-bs-placement='bottom' title='Placer/enlever au-dessus du chat'>
          {this.props.aboveChat ? <i className='bi bi-box-arrow-left' /> : <i className='bi bi-box-arrow-in-right' />}
        </button>
        <button onClick={this.props.handleShowChat} type='button' className='btn btn-sm btn-link mx-1' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Basculer le chat'>
          {this.props.showChat ? <i className='bi bi-arrow-bar-right' /> : <i className='bi bi-arrow-bar-left' />}
        </button>
      </div>
    )
  }
}

// src/app/components/chat-commands/chat-commands.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, model } from "@angular/core";

@Component({
    selector: "app-chat-commands",
    imports: [CommonModule],
    templateUrl: "chat-commands.component.html",
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ChatCommandsComponent {
  public pipActive = model<boolean>();
  public pipAboveChat = model<boolean>();
  public showChat = model<boolean>();

  onChangePipActive() {
    const pipActive = !this.pipActive();
    this.pipActive.set(pipActive);
    if (!pipActive) {
      this.pipAboveChat.set(false);
    }
  }

  onChangeAboveChat() {
    const pipAboveChat = !this.pipAboveChat();
    this.pipAboveChat.set(pipAboveChat);
    if (pipAboveChat) {
      this.pipActive.set(true);
    }
  }

  onChangeShowChat() {
    const showChat = !this.showChat();
    this.showChat.set(showChat);
    if (!showChat) {
      this.pipAboveChat.set(false);
    }
  }
}

@if (pipAboveChat() && showChat()) {
  <button
    type="button"
    class="btn btn-sm mx-1"
    data-bs-toggle="tooltip"
    data-bs-placement="bottom"
    [title]="(pipActive() ? 'Masquer' : 'Afficher') + ' le petit lecteur'"
    (click)="onChangePipActive()">
    @if (pipActive()) {
      <i class="bi bi-eye-slash"></i>
    } @else {
      <i class="bi bi-eye"></i>
    }
  </button>
}
@if (showChat()) {
  <button
    type="button"
    class="btn btn-sm mx-1"
    data-bs-toggle="tooltip"
    data-bs-placement="bottom"
    [title]="
      pipAboveChat() ? 'Enlever du dessus du chat' : 'Placer au-dessus du chat'
    "
    (click)="onChangeAboveChat()">
    @if (pipAboveChat()) {
      <i class="bi bi-box-arrow-left"></i>
    } @else {
      <i class="bi bi-box-arrow-in-right"></i>
    }
  </button>
}

<button
  type="button"
  class="btn btn-sm mx-1"
  data-bs-toggle="tooltip"
  data-bs-placement="bottom"
  [title]="showChat() ? 'Masquer le chat' : 'Afficher le chat'"
  (click)="onChangeShowChat()">
  @if (showChat()) {
    <i class="bi bi-arrow-bar-right"></i>
  } @else {
    <i class="bi bi-arrow-bar-left"></i>
  }
</button>
