// src/Players.jsx
import React, { Component } from 'react'

export class Players extends Component {
  render () {
    const pipClass = []

    if (this.props.flipX) {
      pipClass.push('pip-left')
    } else {
      pipClass.push('pip-right')
    }

    if (this.props.flipY) {
      pipClass.push('pip-top')
    } else {
      pipClass.push('pip-bottom')
    }

    return (
      <div id='players' className={pipClass.join(' ')}>
        {this.props.children}
      </div>
    )
  }
}

// src/app/players/players.component.ts
import { CommonModule } from "@angular/common";
import { Component, Input } from "@angular/core";

export interface Position {
  flipX: boolean;
  flipY: boolean;
}

@Component({
  selector: "app-players",
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      id="players"
      [class.pip-left]="position?.flipX"
      [class.pip-right]="!position?.flipX"
      [class.pip-top]="position?.flipY"
      [class.pip-bottom]="!position?.flipY"
    >
      <ng-content></ng-content>
    </div>
  `,
})
export class PlayersComponent {
  @Input() public position?: Position;
}
